### ISSUE TITLE
OGP:  Caching Message Always Shows

### ISSUE THREAD

**Issue by WillStrohl** [WillStrohl/dnnextensions#31]
The open graph protocol HTML mark-up cannot be loaded from cache. It is suggested that you clear cache in the control panel to fix this issue.

v1.1 worked but upgraded to DNN 6.2.4 and had issues with profile. Upgraded to v1.3. As soon as you add a new page, you get above error with an ugly black stripe on web page saying Will.S .... End of Log.
Clearing cache, etc. nothing helps. Tried v1.2 same problem.
Event Viewer shows error:
InnerException: Object reference not set to an instance of an object.
FileName:
FileLineNumber: 0
FileColumnNumber: 0
Method: WillStrohl.Modules.OpenGraph.OpenGraphStream.Write
StackTrace:
Message: System.NullReferenceException: Object reference not set to an instance of an object. at WillStrohl.Modules.OpenGraph.OpenGraphWriter.OpenGraphStream.Write(Byte[] buffer, Int32 offset, Int32 count)
Not sure what this means, it actually writes to server, config file changes or creates new one.
The pages from v1.1 did not have big ugly black stripe, only newly added pages. I did not have debug turned on.
Uninstalled module to fix error.
comments

brentwilson wrote May 18 at 7:30 AM

I also get this error - Using dnn7.x

ORIGINAL:  https://dnnopengraph.codeplex.com/workitem/12557

**Comment by MaiklT** [comment]
I also get this error, which makes the module unusable.

To help reproduce, here are the OGP settings I use:

Page Title: Home (use Page Settings Title checked)
Page Description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. (use Page Settings checked)
Preferred Url: https://dnndev.me/locale/de-at (Use Default Page Url checked)
Site Locale: de-AT
Preferred Thumbnail: File, some jpeg from the site
Site Name: My Dev Site (Use Default Site checked)
Site Type: Websites: Website
Facebook Admin ID(s): (none)
Facebook Application ID: (none)
Enable Debugging: (not checked)

**Comment by WillStrohl** [comment]
I've put this into my backlog, but I don't know how soon I can get to it.  I'm sorry.  ☹️

**Comment by MaiklT** [comment]
I still have this error:

The open graph protocol HTML mark-up cannot be loaded from cache. It is suggested that you clear cache in the control panel to fix this issue.

Even after clearing the cache or restarting the application pool :-(

Please re-open, thanks!

**Comment by WillStrohl** [comment]
Hello @MaiklT ...  We took another look at this and we're no longer able to reproduce the issue in our test environments.  Are you able to provide any more details about how to reproduce this issue?

**Comment by MaiklT** [comment]
I installed DNN 9.13.6 from scratch (blank website template, German), uploaded some images and then installed the module 2.1.0. I placed a module on the start page.

In the OGP Settings, I entered:

Page Title: Home (Use Page Settings Title: checked)
Page Description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam (Use Page Settings: unchecked, grayed)
Preffered Url: http://xyz.local/ (Use Default Page Url: checked)
Site Locale: de-DE
Preferred Thumbnail: File (a file on your website), selected one of the uploaded images

**Site-Level-Settings**
Site Name: My Website (Use Default Site: checked)
Site Type: Websites: Website
Facebook Admin ID(s): (empty)
Facebook Application ID: (empty)
Enable Debugging?: (checked)

Worked...

On another portal (where I had installed OGP 2.0.0, uninstalled it - because of the error) and installed OGP 2.1.0 later, I get the error with exactly the same settings as above.

_The open graph protocol HTML mark-up cannot be loaded from cache. It is suggested that you clear cache in the control panel to fix this issue._

Debug Window:
_at WillStrohl.Modules.OpenGraph.OpenGraphWriter.OpenGraphStream.Write(Byte[] buffer, Int32 offset, Int32 count)
END OF LOG_

Event Log:
_AbsoluteURL:/de-at/API/PersonaBar/AdminLogs/GetLogTypes
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:bf5dff90-fc21-4afd-8a07-1415e196e19f
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:c/VSOLfdjVbmuX3+VZ641oZeHds=
Message:Object reference not set to an instance of an object.
StackTrace:
   at WillStrohl.Modules.OpenGraph.OpenGraphWriter.OpenGraphStream.Write(Byte[] buffer, Int32 offset, Int32 count)
InnerMessage:
InnerStackTrace:
Source:WillStrohl.Modules.OpenGraph
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: XXXXXX_

**Comment by WillStrohl** [comment]
Hello @MaiklT :

We're still unable to duplicate the issue now.  Here's a response from my team.  

> I have tested the configuration described by the customer and, like him, it worked fine in my environment. However, the customer mentions that the issue persists on a site where he had the module previously installed. Even after uninstalling and reinstalling it, it still presents the error.
> 
> In my case, I have not been able to replicate that specific situation. In fact, when installing the module with the fix in a similar environment (with the error described), it worked fine.
> 
> Here is a demo with the test performed. [OpenGraph 9136 test.mp4](https://app.screencast.com/67BoyKQeXVppwc)
> 
> The only thing I can think of as a possible cause is to check if the Open Graph protocol is enabled on your site. Previously, this error was caused because the file responsible for enabling this protocol was not being copied during installation, which prevented Open Graph from being enabled. It is possible that on your site this protocol is not yet enabled, which could be causing the problem.
> ![image](https://github.com/user-attachments/assets/a62742d2-6226-45c6-aca9-75dd69a29748)
> I hope this suggestion helps to identify the cause of the problem.
